### ISSUE TITLE
DateTime Type Incorrect

### ISSUE THREAD

**Issue by cliffburdick** [ClickHouse/clickhouse-cpp#6]
The clickhouse manual says:

"Date with time. Stored in four bytes as a Unix timestamp (unsigned)"
https://clickhouse-docs.readthedocs.io/en/latest/data_types/datetime.html

However, in the client code, this is defined as time_t, which is 64 bits on 64-bit systems:

```void Append(const std::time_t& value);```

**Comment by Enmk** [comment]
Hi @cliffburdick !

Yep, date/datetime values are passed around as `time_t` (I believe this is done to simplify integration with crt-functions and to have a specific type rather than just some `int`), **but** those are stored as `uint16_t`/`uint32_t`:

https://github.com/ClickHouse/clickhouse-cpp/blob/7cb0a699a59f421f694c58e1217c8343ae2876f1/clickhouse/columns/date.cpp#L12

https://github.com/ClickHouse/clickhouse-cpp/blob/7cb0a699a59f421f694c58e1217c8343ae2876f1/clickhouse/columns/date.cpp#L58

The same way values are stored in ClickHouse itself.

**Comment by cliffburdick** [comment]
Thanks @enmk! I didn't know if this was intentional to truncate or not, so that makes sense. By the way, is the artpaul or this repo the official c++ client? I noticed both appear to be actively maintained, while this one is a fork.

**Comment by Enmk** [comment]
YW. This one is official.
